version: '2'
services:
    orchestra:
        build: .
        image: xoa-ce-build
        ports:
            - "8000:8000"
        depends_on:
            - redis
        environment:
            - USER=node
            - DEBUG=xo:main
        volumes:
            - ./volumes/xo-server:/storage
        privileged: true
    redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - ./volumes/redis:/data
