version: '2'
services:
    orchestra:
        image: ezka77/xen-orchestra-ce
        ports:
            - "8000:80"
        depends_on:
            - redis
        environment:
            - DEBUG=xo:main
        volumes:
            - ./volumes/xo-server:/storage
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - ./volumes/redis:/data
