version: '3'
services:
    orchestra:
        restart: unless-stopped
        image: ezka77/xen-orchestra-ce
        container_name: XO_server
        ports:
            - "8000:8000"
        depends_on:
            - redis
        environment:
            - DEBUG=xo:main
            - NODE_ENV=production
            - XOA_PLAN=5
        volumes:
            - ./volumes/xo-server:/storage
    redis:
        restart: unless-stopped
        container_name: XO_redis
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - ./volumes/redis:/data
