# Example XO-Server configuration.
#
# This file is automatically looking for at the following places:
# - `$HOME/.config/xo-server/config.toml`
# - `/etc/xo-server/config.toml`
#
# The first entries have priority.
#
# Note: paths are relative to the configuration file.

#=====================================================================

# HTTP proxy configuration used by xo-server to fetch resources on the Internet.
#
# See: https://github.com/TooTallNate/node-proxy-agent#maps-proxy-protocols-to-httpagent-implementations
# httpProxy = '${XO_PROXY_HTTPPROXY}'

# List of host names (optionally with a port), separated by commas, for which
# the proxy above will not be used.
#
# noProxy = '${XO_PROXY_NOPROXY}'

#=====================================================================

# It may be necessary to run XO-Server as a privileged user (e.g. `root`) for
# instance to allow the HTTP server to listen on a
# [privileged ports](http://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html).
#
# To avoid security issues, XO-Server can drop its privileges by changing the
# user and the group is running with.
#
# Note: XO-Server will change them just after reading the configuration.

# User to run XO-Server as.
#
# Note: The user can be specified using either its name or its numeric
# identifier.
#
# Default: undefined
#user = '${XO_USER_USER}'

# Group to run XO-Server as.
#
# Note: The group can be specified using either its name or its numeric
# identifier.
#
# Default: undefined
# group = '${XO_USER_GROUP}'

#=====================================================================

# Directory containing the database of XO.
# Currently used for logs.
#
# Default: '/var/lib/xo-server/data'
#datadir = '${XO_DB_DATADIR}'

#=====================================================================

Include=/etc/zabbix/web_config.toml

#=====================================================================

# Uncomment this section to export the logs to an external syslog
#[logs.transport.syslog]
#target = '${XO_SYSLOG_TARGET}'

#=====================================================================

# Connection to the Redis server.
[redis]
# Unix sockets can be used
#
# Default: undefined
#socket = '${XO_REDIS_SOCKET}'

# Syntax: redis://[db[:password]@]hostname[:port][/db-number]
#
# Default: redis://localhost:6379/0
#uri = '${XO_REDIS_URI}'

# List of aliased commands.
#
# See http://redis.io/topics/security#disabling-of-specific-commands
#renameCommands:
#  del = '3dda29ad-3015-44f9-b13b-fa570de92489'
#  srem = '3fd758c9-5610-4e9d-a058-dbf4cb6d8bf0'

#=====================================================================

# Configuration for remotes
[remoteOptions]
# Directory used to mount remotes
#
# Default: '/run/xo-server/mounts'
#mountsDir = '${XO_REMOTES_MOUNTSDIR}'

# Use sudo for mount with non-root user
#
# Default: false
#useSudo = ${XO_RREMOTES_USESUDO}

#=====================================================================

# Configuration for plugins
[plugins]
# Each configuration is passed to the dedicated plugin instance
#
# Syntax: [plugins.<pluginName>]